### ISSUE TITLE
Alfresco docker-compose is not working 

### ISSUE THREAD

**Issue by kphareesh1994** [Alfresco/acs-community-deployment#100]
I am using  docker compose to deploy Alfresco content service using user name "admin" and password "admin" facing  ""Your authentication details haven't been recognized or Alfresco Content Services may not be available at this time "" and also getting error while building the docker-compose facing illegal access stopping the application. please help in solving the issue

**Comment by dolgushin** [comment]
Good afternoon! I confirm that the problem really exists. It has not yet been resolved.

**Comment by dolgushin** [comment]
It is enough to add to docker-compose 
 volumes:
- /opt/alfresco/db/postgres-data:/var/lib/postgresql/data 
and execute docker-compose down & & docker-compose up -d error immediately appears "Your authentication details haven't been recognized or Alfresco Content Services may not be available at this time."

**Comment by carrodher** [comment]
Same issue here `admin`/`admin` doesn't work as credentials
![Screen Shot 2020-05-14 at 11 54 36](https://user-images.githubusercontent.com/13216600/81920582-b11b0000-95d9-11ea-8167-fc99478ac072.png)

In the same way, there are a lot of errors in the logs, both in solr and share:
```
...
solr6_1               | 2020-05-14 09:55:40.037 ERROR (org.alfresco.solr.AlfrescoCoreAdminHandler@23cd4ff2_Worker-24) [   ] o.a.s.t.AclTracker [alfresco / ACL@1538019286 / IT #1589450140017] Tracking failure. See the stacktrace below for further details.
solr6_1               | java.net.UnknownHostException: alfresco
solr6_1               | 	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:220)
solr6_1               | 	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
solr6_1               | 	at java.base/java.net.Socket.connect(Socket.java:609)
solr6_1               | 	at java.base/java.net.Socket.connect(Socket.java:558)
solr6_1               | 	at java.base/java.net.Socket.<init>(Socket.java:454)
solr6_1               | 	at java.base/java.net.Socket.<init>(Socket.java:306)
solr6_1               | 	at org.apache.commons.httpclient.protocol.DefaultProtocolSocketFactory.createSocket(DefaultProtocolSocketFactory.java:80)
solr6_1               | 	at org.apache.commons.httpclient.protocol.DefaultProtocolSocketFactory.createSocket(DefaultProtocolSocketFactory.java:122)
solr6_1               | 	at org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:707)
solr6_1               | 	at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.open(MultiThreadedHttpConnectionManager.java:1361)
solr6_1               | 	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:387)
solr6_1               | 	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
solr6_1               | 	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
solr6_1               | 	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
solr6_1               | 	at org.alfresco.httpclient.AbstractHttpClient.executeMethod(AbstractHttpClient.java:135)
solr6_1               | 	at org.alfresco.httpclient.AbstractHttpClient.sendRemoteRequest(AbstractHttpClient.java:111)
solr6_1               | 	at org.alfresco.httpclient.HttpClientFactory$DefaultHttpClient.sendRequest(HttpClientFactory.java:432)
solr6_1               | 	at org.alfresco.solr.client.SOLRAPIClient.callRepository(SOLRAPIClient.java:1590)
solr6_1               | 	at org.alfresco.solr.client.SOLRAPIClient.getAclChangeSets(SOLRAPIClient.java:184)
solr6_1               | 	at org.alfresco.solr.tracker.AclTracker.checkRepoAndIndexConsistency(AclTracker.java:347)
solr6_1               | 	at org.alfresco.solr.tracker.AclTracker.trackRepository(AclTracker.java:312)
solr6_1               | 	at org.alfresco.solr.tracker.AclTracker.doTrack(AclTracker.java:95)
solr6_1               | 	at org.alfresco.solr.tracker.AbstractTracker.track(AbstractTracker.java:203)
solr6_1               | 	at org.alfresco.solr.tracker.TrackerJob.execute(TrackerJob.java:47)
solr6_1               | 	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
solr6_1               | 	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
...
share_1               | 2020-05-14 09:55:55,675  INFO  [webscripts.connector.RemoteClient] [http-nio-8080-exec-7] Exception calling (GET) http://alfresco:8080/alfresco/s/remoteadm/has/alfresco/site-data/chrome/.xml?s=sitestore
share_1               |  java.net.UnknownHostException: alfresco
share_1               | 	at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:797)
share_1               | 	at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1505)
share_1               | 	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1364)
share_1               | 	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1298)
share_1               | 	at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
share_1               | 	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:112)
share_1               | 	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:374)
share_1               | 	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
share_1               | 	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
share_1               | 	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
share_1               | 	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
share_1               | 	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
share_1               | 	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
share_1               | 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
share_1               | 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
share_1               | 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
share_1               | 	at org.springframework.extensions.webscripts.connector.RemoteClient.service(RemoteClient.java:1167)
```

Everything using default docker-compose.

**Comment by dolgushin** [comment]
Default docker-compose  work incorrectly. I created a configuration that works as it should.
version: "2"

 

services:

    alfresco:

        image: alfresco/alfresco-content-repository-community:6.2.1-A7

        mem_limit: 1500m

        environment:

            JAVA_OPTS: "

                -Ddb.driver=org.postgresql.Driver

                -Ddb.username=alfresco

                -Ddb.password=alfresco

                -Ddb.url=jdbc:postgresql://postgres:5432/alfresco

                -Dsolr.host=solr6

                -Dsolr.port=8983

                -Dsolr.secureComms=none

                -Dsolr.base.url=/solr

                -Dindex.subsystem.name=solr6

                -Dshare.host=127.0.0.1

                -Dshare.port=8080

                -Dalfresco.host=localhost

                -Dalfresco.port=8080

                -Daos.baseUrlOverwrite=http://localhost:8080/alfresco/aos

                -Dmessaging.broker.url=\"failover:(nio://activemq:61616)?timeout=3000&jms.useCompression=true\"

                -Ddeployment.method=DOCKER_COMPOSE

                -DlocalTransform.core-aio.url=http://transform-core-aio:8090/

                -Dalfresco-pdf-renderer.url=http://transform-core-aio:8090/

                -Djodconverter.url=http://transform-core-aio:8090/

                -Dimg.url=http://transform-core-aio:8090/

                -Dtika.url=http://transform-core-aio:8090/

                -Dtransform.misc.url=http://transform-core-aio:8090/

                -Dcsrf.filter.enabled=false

                -Xms1500m -Xmx1500m

                "

        volumes:

            - ./data/alf-repo-data:/usr/local/tomcat/alf_data

            - ./logs/alfresco:/usr/local/tomcat/logs

 

    transform-core-aio:

        image: alfresco/alfresco-transform-core-aio:2.2.1

        mem_limit: 1536m

        environment:

            JAVA_OPTS: " -Xms256m -Xmx1536m"

        ports:

            - 8090:8090

 

    share:

        image: alfresco/alfresco-share:6.2.1-RC2

        mem_limit: 1g

        environment:

            REPO_HOST: "alfresco"

            REPO_PORT: "8080"

            JAVA_OPTS: "

                -Xms500m

                -Xmx500m

                -Dalfresco.host=localhost

                -Dalfresco.port=8080

                -Dalfresco.context=alfresco

                -Dalfresco.protocol=http

                "

        volumes:

            - ./logs/share:/usr/local/tomcat/logs

 

    postgres:

        image: postgres:11.4

        mem_limit: 512m

        environment:

            - POSTGRES_PASSWORD=alfresco

            - POSTGRES_USER=alfresco

            - POSTGRES_DB=alfresco

        command: postgres -c max_connections=300 -c log_min_messages=LOG

        ports:

            - 5432:5432

        volumes:

            - ./psql:/var/lib/postgresql/data

            - ./logs/postgres:/var/log/postgresql

 

    solr6:

        image: alfresco/alfresco-search-services:1.4.2

        mem_limit: 2g

        environment:

            #Solr needs to know how to register itself with Alfresco

            - SOLR_ALFRESCO_HOST=alfresco

            - SOLR_ALFRESCO_PORT=8080

            #Alfresco needs to know how to call solr

            - SOLR_SOLR_HOST=solr6

            - SOLR_SOLR_PORT=8983

            #Create the default alfresco and archive cores

            - SOLR_CREATE_ALFRESCO_DEFAULTS=alfresco,archive

            #HTTP by default

            - ALFRESCO_SECURE_COMMS=none

            - "SOLR_JAVA_MEM=-Xms2g -Xmx2g"

        ports:

            - 8083:8983 #Browser port

        volumes:

            - ./data/solr-data:/opt/alfresco-search-services/data

            - ./data/solr-data/keystores:/opt/alfresco-search-services/keystores

 

    activemq:

        image: alfresco/alfresco-activemq:5.15.8

        mem_limit: 1g

        ports:

            - 8161:8161 # Web Console

            - 5672:5672 # AMQP

            - 61616:61616 # OpenWire

            - 61613:61613 # STOMP

        volumes:

        #- ./activemq-data:/opt/activemq/conf

            - ./activemq-data:/data/activemq

            - ./activemq-data:/var/log/activemq

 

    proxy:

        image: alfresco/acs-community-ngnix:1.0.0

        mem_limit: 128m

        depends_on:

            - alfresco

        ports:

            - 8080:8080

        links:

            - alfresco

            - share

**Comment by gavincornwell** [comment]
Firstly, thank you for raising this issue and apologies for the time it's taken to respond.

As you may have seen from the recent blog post (https://hub.alfresco.com/t5/alfresco-content-services-blog/acs-community-repositories-consolidation/ba-p/302770) we have been consolidating the deployment repositories and this one is being archived.

The latest default version of the community docker compose file can now be found here: https://github.com/Alfresco/acs-deployment/blob/master/docker-compose/community-docker-compose.yml

Please try this file and create a new issue in the https://github.com/Alfresco/acs-deployment repository if the problem you saw still occurs.
