### ISSUE TITLE
not able to open localhost:8080/share

### ISSUE THREAD

**Issue by pankajmalkani** [Alfresco/acs-community-deployment#114]
Dear Sir/Madam,
when i have installed docker successfully and pulled out alfresco community edition using docker-compose up command, it has started downloading all the files , installing different softwares etc and then it never stops. When i click on localhost:8080/share, it takes a lot of time and throws an error 504 gateway time out .
Please let me know the solution regarding this mentioned above.

Please note that it's urgent basis as we need to show the demo to our client ASAP.

**Comment by henrysimon** [comment]
try using ip instead of name, let say the vm where the docker hostname is mydocker it will fail when i browse to http://mydocker:8080
but success if i use http://192.168.1.20:8080

**Comment by gavincornwell** [comment]
As you may have seen from the recent blog post (https://hub.alfresco.com/t5/alfresco-content-services-blog/acs-community-repositories-consolidation/ba-p/302770) we have been consolidating the deployment repositories and this one is being archived.

If you are still experiencing issues after trying the latest code in https://github.com/Alfresco/acs-deployment please create a new issue in that repository.
