### ISSUE TITLE
Problem with minikube+helm instructions

### ISSUE THREAD

**Issue by RogerParkinson** [Alfresco/acs-community-deployment#118]
Trying to follow through the instructions to install w minikube+helm. I'm not v familiar w helm so I easily get stuck.

Anyway

```
helm init --service-account tiller
Error: unknown command "init" for "helm"
```
which may be causing the next issue:

```
helm install stable/nginx-ingress --set rbac.create=true
Error: must either provide a name or specify --generate-name
```
So I tried:
```
helm install stable/nginx-ingress --set rbac.create=true --generate-name
Error: failed to download "stable/nginx-ingress" (hint: running `helm repo update` may help)
```
I already ran the update (as per instructions) and verified etc. I took a guess and tried this:
```
helm install alfresco-stable/nginx-ingress --set rbac.create=true --generate-name
Error: failed to download "alfresco-stable/nginx-ingress" (hint: running `helm repo update` may help)
```
No idea where to go next

**Comment by gavincornwell** [comment]
Firstly, thank you for raising this issue and apologies for the time it's taken to respond.

As you may have seen from the recent blog post (https://hub.alfresco.com/t5/alfresco-content-services-blog/acs-community-repositories-consolidation/ba-p/302770) we have been consolidating the deployment repositories and this one is being archived.

We now recommend using Docker for Desktop for local development/testing and we have a new guide for that in the consolidated repository: https://github.com/Alfresco/acs-deployment/blob/master/docs/helm/docker-desktop-deployment.md.

If you are still having problems please create an issue in the consolidated repository.
