### ISSUE TITLE
Can deploy Alfresco

### ISSUE THREAD

**Issue by ogemperle** [Alfresco/acs-community-deployment#119]
Dear Community

I work at the Bern University of Applied Sciences and a professor uses Alfresco in his classes. At the moment he uses an old version and I’ve now to update it.
I tried to deploy the community version, but I receive always an error message.

To the class I’ve prepared a Kubernetes Cluster based on 3 Ubuntu 18.04 Servers, one master and two workers:

Cluster information:
kubectl get nodes
NAME             STATUS   ROLES    AGE   VERSION
k8s-172-16-1-7   Ready    master   22h   v1.16.3
k8s-172-16-1-8   Ready    <none>   22h   v1.16.3
k8s-172-16-1-9   Ready    <none>   22h   v1.16.3

kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:23:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.12", GitCommit:"17c50ce2d686f4346924935063e3a431360e0db7", GitTreeState:"clean", BuildDate:"2020-06-26T03:33:27Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

helm version
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}

Steps until the error

sudo snap install helm --classic
helm 3.2.4 from Snapcrafters installed

helm repo add alfresco-incubator http://kubernetes-charts.alfresco.com/incubator
"alfresco-incubator" has been added to your repositories

helm repo update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "alfresco-incubator" chart repository
Update Complete. ⎈ Happy Helming!⎈ 

export ALF_ADMIN_PWD=$(printf %s 'MyTestPwd' | iconv -t UTF-16LE | openssl md4 | awk '{ print $1}')
export ALF_DB_PWD='MyDbPwd'
helm install my-acs alfresco-incubator/alfresco-content-services-community --set repository.adminPassword="$ALF_ADMIN_PWD" --set postgresql.postgresPassword="$ALF_DB_PWD"
Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1"

I searched about this error and in some forums and I found something like “You should use HELM 2”.

I started again with HELM 2, but I received another error message.
helm install alfresco-incubator/alfresco-content-services-community
Error: no available release name found

Can you help me?

Best Regards
Oscar Gemperle

**Comment by mmuller88** [comment]
Yeah the current community isn't compatible with k8s 1.16

**Comment by mmuller88** [comment]
And this issue here is a duplicate: https://github.com/Alfresco/acs-community-deployment/issues/93

**Comment by gavincornwell** [comment]
Firstly, thank you for raising this issue and apologies for the time it's taken to respond.

As you may have seen from the recent blog post (https://hub.alfresco.com/t5/alfresco-content-services-blog/acs-community-repositories-consolidation/ba-p/302770) we have been consolidating the deployment repositories and this one is being archived.

Kubernetes 1.16 (and Helm 3) support has been added to the helm charts provided in https://github.com/Alfresco/acs-deployment.
