### ISSUE TITLE
Share module does not work on a custom port

### ISSUE THREAD

**Issue by vteryaev** [Alfresco/acs-community-deployment#127]
I faces the issue that it's  impossible to reconfigure Alfresco community in Docker to work on a port different from the default 8080. I checked out the docker compose from https://github.com/Alfresco/acs-community-deployment.git and changed the following properties in alfresco and share modules: share.port=8084, alfresco.port=8084 as well as port mapping for a proxy module to 8084:8080.

Then run it.

There are 2 issues with share module:

1) somehow when I try to access it using http://localhost:8084/share I keep redirecting to http://localhost:8080/share.

2) magically the page http://localhost:8084/share/page  works fine and displays a login form. But it is impossible to login because of 500 error (Something's wrong with this page...). Share logs says the following:

Possible CSRF attack noted when asserting referer header.

[logs.txt](https://github.com/Alfresco/acs-community-deployment/files/5144805/logs.txt)

**Comment by smshafa** [comment]
I also change the proxy port from 8080 to 8086 and the following message is shown on the console:
proxy_1               | 172.21.0.1 - - [27/Sep/2020:06:20:01 +0000] "GET /favicon.ico HTTP/1.1" 504 569 "http://localhost:8086/share/page" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36"

proxy_1               | 2020/09/27 06:20:52 [error] 7#7: *12 upstream timed out (110: Operation timed out) while reading response header from upstream, client: 172.21.0.1, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.21.0.3:8080/favicon.ico", host: "localhost:8086", referrer: "http://localhost:8086/alfresco/"

**Comment by abhinavmishra14** [comment]
Have a look at these threads:
https://hub.alfresco.com/t5/alfresco-content-services-forum/alfresco-docker-share-port-change/td-p/292312

https://hub.alfresco.com/t5/alfresco-content-services-forum/error-with-the-changing-of-the-default-ports-from-8080-to-19180/m-p/300460#M20341

**Comment by gavincornwell** [comment]
Firstly, thank you for raising this issue and apologies for the time it's taken to respond.

As you may have seen from the recent blog post (https://hub.alfresco.com/t5/alfresco-content-services-blog/acs-community-repositories-consolidation/ba-p/302770) we have been consolidating the deployment repositories and this one is being archived.

It looks like you have been given some further resources to help solve the issue so I'm going to close this issue. 

Please refer to the new docker compose documentation (https://github.com/Alfresco/acs-deployment/tree/master/docs/docker-compose). If the problem still exists or you need further help please raise a new issue in https://github.com/Alfresco/acs-deployment.
