### ISSUE TITLE
FYI SOLR_ALFRESCO_HOST set to wrong host name

### ISSUE THREAD

**Issue by sanderPostma** [Alfresco/acs-community-deployment#31]
I deployed a test cluster using helm script alfresco-incubator/alfresco-content-services-community
I ran into an issue where the search pod logged an UnknownHostException to host "alfresco-cs-incubator-alfresco-content-services-community-repository" That looks like a longer name which does not exists. 
I'm not sure in which file this is set, but I could override by adding parameter:
--set alfresco-search.environment.SOLR_ALFRESCO_HOST="alfresco-cs-incubator-alfresco-cs-ce-repository" 
But this is a small misconfiguration that you may want to iron out for the next release. I ran into this error when calling "Recent files" from the adf-content-app, it got stuck.

**Comment by derekhulley** [comment]
Thank you for bringing this to our attention.
Could you raise an issue at https://issues.alfresco.com (Alfresco project) for us, please?  We'll be happy to follow up and resolve the issue.

**Comment by derekhulley** [comment]
Thank you for bringing this to our attention.
Could you raise an issue at https://issues.alfresco.com with the necessary details, please?  We will follow up and resolve.

**Comment by derekhulley** [comment]
https://issues.alfresco.com/jira/browse/ALF-22041

**Comment by AFaust** [comment]
This is actually the same issue as https://github.com/Alfresco/acs-deployment/pull/24 which has already been fixed for Enterprise.
