### ISSUE TITLE
Link from readme points to acs enterprise

### ISSUE THREAD

**Issue by albertorugnone** [Alfresco/acs-community-deployment#49]
Hi guys,
I see that link to docker-compose in this README.txt points to ACS enterprise. Maybe there are other links like that.

**Comment by killerboot** [comment]
Hi @albertorugnone!
Thanks, for raising this. I'll cc it to @anxumalo to take a look.

**Comment by anxumalo** [comment]
Hi @albertorugnone!
Thank you for bringing this to our attention. Apologies for taking so long to get this completed. Please see the updates in the linked PR.
