### ISSUE TITLE
Can not pull alfresco-digital-workspace

### ISSUE THREAD

**Issue by shenkonghui** [Alfresco/acs-community-deployment#59]
[root@centos ~]# docker pull quay.io/alfresco/alfresco-digital-workspace:1.1
Error response from daemon: unauthorized: access to the requested resource is not authorized
[root@centos ~]#

**Comment by killerboot** [comment]
Hi, digital-workspace is not a community product. As it is enterprise only, you will need a valid account in quay.io created by Alfresco support (support@alfresco.com)
