### ISSUE TITLE
Nginx Docker Image availability

### ISSUE THREAD

**Issue by aborroy** [Alfresco/acs-community-deployment#61]
It looks like "alfresco/acs-community-ngnix" is not available for Community users?

Where can be found this Docker Image?

**Comment by killerboot** [comment]
Hi @aborroy , the image is here: https://hub.docker.com/r/alfresco/acs-community-ngnix

**Comment by aborroy** [comment]
The image is in Docker Hub, but the source code is not available, so people cannot see what we are providing.

**Comment by killerboot** [comment]
ah, you mean the Dockerfile
It is on a branch of acs-ingress project:
https://github.com/Alfresco/acs-ingress/tree/acs-community-ingress

**Comment by aborroy** [comment]
Should we include this link in README file?

**Comment by killerboot** [comment]
Good point. I'll cc that to @anxumalo and @anechifor as it was added recently and there will be more documentation changes available
