### ISSUE TITLE
Alfresco  6.2.0-A9 Helm Chart:Failed to connect or to read the response from T-Engine

### ISSUE THREAD

**Issue by susimsek** [Alfresco/acs-community-deployment#78]
Hi,I get the error in the picture when I deploy the alfresco helm chart distribution.

I run this command to deploy chart .

**helm install . --name alfresco --namespace alfresco**

Only alfresco-content-repository-community pod error occurs

Error;

![image](https://user-images.githubusercontent.com/46258776/65819859-39ef5200-e22a-11e9-9912-bf1e23d5f6c2.png)

Helm Chart Files;
[alfresco.zip](https://github.com/Alfresco/acs-community-deployment/files/3665767/alfresco.zip)

**Comment by alandavis** [comment]
Thank you for raising this issue.
We are working on this as part of https://issues.alfresco.com/jira/browse/REPO-4672
