### ISSUE TITLE
Alfresco Helm 6.2.0-A9 : Remain Connected to database PostgreSQL 

### ISSUE THREAD

**Issue by susimsek** [Alfresco/acs-community-deployment#80]
Hi,postresql remains connected when I deploy alfrescon's 6.2.0-A9 helm chart distribution and then the alfresco pod restarts.Alfresco pod is constantly restarting, and it never starts successfully

i run this command.

helm install . --name alfresco --namespace alfresco

![image](https://user-images.githubusercontent.com/46258776/66048308-f8b0b800-e531-11e9-9f05-d74ca5103a51.png)
![image](https://user-images.githubusercontent.com/46258776/66049219-ad97a480-e533-11e9-9635-5d57da948ace.png)

[alfresco.zip](https://github.com/Alfresco/acs-community-deployment/files/3681343/alfresco.zip)

**Comment by alandavis** [comment]
Hi susimsek

Are you able to provide details of the environment on which you were trying to run 6.2.0-A9? Although our 'A' alpha/incubator versions are really for our own use, you should not have had problems using this image as our automated tests using AWS passed. Were you using Minikube by any chance? For your information there are now later stable version https://github.com/Alfresco/acs-community-deployment/blob/master/docs/helm-chart-releases.md.

Regards Alan
Linked Issue: https://issues.alfresco.com/jira/browse/REPO-4918

**Comment by gavincornwell** [comment]
As you may have seen from the recent blog post (https://hub.alfresco.com/t5/alfresco-content-services-blog/acs-community-repositories-consolidation/ba-p/302770) we have been consolidating the deployment repositories and this one is being archived.

We have also changed the way we deploy previous versions of the product. Please refer to the new Helm documentation (https://github.com/Alfresco/acs-deployment/blob/master/docs/helm/README.md). If the problem still exists please raise a new issue in https://github.com/Alfresco/acs-deployment.
