### ISSUE TITLE
Kubernetes Version 1.16 Removes Deprecated APIs

### ISSUE THREAD

**Issue by number133** [Alfresco/acs-community-deployment#93]
Installing acs via helm on 1.16 gives the following error: 
`helm install alfresco-stable/alfresco-content-services-community --set externalProtocol="http" --set externalHost="acs-community.local" --set externalPort="32748"`
`Error: validation failed: unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1"`

[This](https://www.ibm.com/cloud/blog/announcements/kubernetes-version-1-16-removes-deprecated-apis) might be the cause.

What can be done to fix it?

**Comment by deas** [comment]
@number133 Things appear to be moving pretty slow here. Guess your best bet is to fork the repo and apply needed changes yourself. The issue at hand can be fixed by changing `extensions/v1beta1` to `apps/v1`. IIRC, the next issue surfacing is that `Deployment` needs a `selector`.

**Comment by gavincornwell** [comment]
Firstly, thank you for raising this issue and apologies for the time it's taken to respond.

As you may have seen from the recent blog post (https://hub.alfresco.com/t5/alfresco-content-services-blog/acs-community-repositories-consolidation/ba-p/302770) we have been consolidating the deployment repositories and this one is being archived.

Kubernetes 1.16 support has been added to the helm charts provided in https://github.com/Alfresco/acs-deployment
